### ISSUE TITLE
如果使用rbd作为持久化存储，应该怎么集成呢If you use rbd as a persistent store, how should you integrate it?

### ISSUE THREAD

**Issue by amateu** [cuishuaigit/k8s-kafka#1]
如果使用rbd作为持久化存储，对于kafka我需要建3个pvc
  volumeClaimTemplates: 这里我改怎么写，求指教
If use rbd as a persistent store, I need to build 3 pvc for kafka.
   volumeClaimTemplates: Here I am changing how to write, ask for advice

**Comment by cuishuaigit** [comment]
> 如果使用rbd作为持久化存储，对于kafka我需要建3个pvc
> volumeClaimTemplates: 这里我改怎么写，求指教
> If use rbd as a persistent store, I need to build 3 pvc for kafka.
> volumeClaimTemplates: Here I am changing how to write, ask for advice

there's somethinf different is that create storageclass,you can follow:
`kind: StorageClass

 metadata:

  name: dynamic

provisioner: kubernetes.io/rbd

parameters:

  monitors: 10.19.26.9:6789

  adminId: admin

  adminSecretName: ceph-admin-secret

  adminSecretNamespace: kafka

  pool: kafka

  userId: kafka

  userSecretName: ceph-kafka-secret

  fsType: ext4

  imageFormat: "1"` 

volumeClaimTemplates just same as  nfs
@amateu

**Comment by amateu** [comment]
@cuishuaigit 
Thank you, I have solved it.The problem is that when I use kubernetes.io/rbd to integrate rbd storgeclass, kube dynamically creates a disk error, because kube-controller-manager does not integrate ceph-common. Finally, I replaced the image of kube-controller-manager.yaml in /etc/kubernetes/manifests.
# image: k8s.gcr.io/kube-controller-manager: v1.13.6
     Image: gcr.io/google-containers/hyperkube: v1.13.6

**Comment by cuishuaigit** [comment]
@amateu 
Hi, amateu! I review  some issue and view the source code, leaarn about that when use ceph rbd as storage,controller-manager need rbd to create ceph image,but Official image does not contain
rbd.so i think gcr.io/google-containers/hyperkube: v1.13.6 just a temporary plan
because  when  use kubernetes-1.14  i can't find rbd in controller-manager. the good way to use ceph rbd is that as nfs use quay.io/external_storage,rbd must use quay.io/external_storage/rbd-provisioner:latest. the image tag must according to your ceph version

**Comment by cuishuaigit** [comment]
i will update this repo add  how to use ceph rbd, thank you commit the issue

**Comment by amateu** [comment]
@cuishuaigit thanks for you answer。I will test gcr.io/external_storage later.
I don't understand that gcr.io/google-containers/hyperkube: v1.13.6 is a temporary solution.Has it been updated to 1.15?
